### ISSUE TITLE
no sdo response recieved

### ISSUE THREAD

**Issue by HayfaNc** [bggardner/canopen-rpi#4]
I have a real client (master) and I'm working on creating a virtual canopen slave to communicate with this existing master by sending some messages.
When running my script and waiting for my virtual slave to enter to the operationnal mode I keep getting this error "no sdo response recieved". 
As far as I know, I need to send sdo responses to the master's requests so the master can detect my virtual device and start receiving messages.
when I use this function `node.sdo.send_response(data)` the master still can't detect my device.

How can I fix this problem? is there any example for a virtual canopen slave or a virtual sdo server?

**Comment by bggardner** [comment]
There are plenty of slave ("node") [examples](https://github.com/bggardner/canopen-rpi/tree/master/examples), but to help diagnose your problem, I'll need to know more details about the SDO request from your master, such as the index/subindex it is requesting.  What is the model of the master device?  "no sdo response received" is fairly vague, but I assume that it cannot communicate with the slave at all since normally the slave would respond with an SDO abort if something was wrong.  Be sure the master and slave can transmit/receive CAN messages on the same bus (and use the same bitrate) before troubleshooting CANopen.
